---
name: Checks #this name will appear in github

on: [push] #the trigger

jobs:
  test-lint: #id of the job
  runs-on: ubuntu-20.04 #the runner
  steps:
    - name: Login to Docker Hub
      users: docker/login-action@v1 #pre-provided action - docker config/container. officially provided
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    - name: Checkout
      uses: actions/checkout@v2 #checkout to the code which came
    - name: Test
      run: docker compose run --rm app sh -c "python manage.py test" #test of the code inside
    - name: Lint
      run: docker compose run --rm app sh -c "flake8"